apiVersion: v1
kind: Secret
metadata:
    name: node-info-secrets
    namespace: node-info-production
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:2TLrOo6TLYeQyoOA2lRNQJQYC3zsnrIG51kUNJg=,iv:7SpMTm78g8hkBLQsN7jr1ACsRDezGpWL6Os4G878h8M=,tag:L+MBl1GCOQX+oPFy8YJT+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dU9rN0hTOXB5L1VESjli
            MlpBREdOa1BsZWJoaWZ5U1IzVm9zYXdkODNNCmNqVzBpalJLcndyYThXc2Z1TjJZ
            WE05Z0ZRSUFDNFRhU2dtVWhlbDZOM00KLS0tICtCQjhsYnFCcmtpS0Q2RngycEtK
            ZE1LRFRWYkRZVHE3TkpUS1dhc3laUFkKgIxLrPi7DKqt0RSKna/Spb0IzcQsTZsB
            vnH7J500bQRlwKFJgM+EV4WFH1CMyqSDFpp0g8LHXLL0JV7onnCmag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gkl9eta2jwwym9xrtkc4034jgr9wv2aw84wvtacfh7vn3f200ersnf4tsj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T10:35:03Z"
    mac: ENC[AES256_GCM,data:tfIY8H3E13mSC/6Naqbw8+bXYCiy4uGHrav6b9k3k/0/jZ9vO87nrUvz6WElWvkV5Z/Jc8IPLSQz5jqRLtGRESnuxlDvuOEh8AzoEphfMnuWMBi739v9quGQchKxV2Gb4UEA5Z7eGcCPd3sbDwcQn0cxMJj+l6258RgGaydCZgk=,iv:FB436RLYPjImcxi2pt+wXTgACq27SDSuLnmdYTSo9K8=,tag:bbUXjE07BXz2/mgk9SB5ug==,type:str]
    version: 3.13.2
