apiVersion: v1
kind: Secret
metadata:
    name: node-info-secrets
    namespace: node-info-staging
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:TPmDHqCbTSdP4h3MqOYKYxoT1T+/U6E3xoo=,iv:PA7OktygjafYl15qDK0hRiyhHG+jbaIKwg2rbqy1YTU=,tag:Fc719BDJAr0KcOSGeZ10oA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdjluS2U5dmtSZzVPaFBu
            QjhFSEsyOWtJaXlUSzdYUGlmV2s1V3JvQjJFCkNuZkhYWDhBYUl0Nmo5akZ6R0lp
            Mk5CT05TSE5FeHc2MlM4MTJwZEdqdDAKLS0tIEFJYUZLNnVEQWppd095L0lSa2hy
            N25pdVBIaGduWlczaDR0dUJrSytOVFkKpCqute7uMSmdx1LCIQzYlp84TrqAPIo6
            NM5asjdmIup29NCjNnQQy01iPpG7ku+w4CepHl2WU4TBaa3RPAL4vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gzp3qquwxqwmhzuk5zhx32xajsjgf5npclwsze988h0hvnuuncfquwtef3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T10:35:03Z"
    mac: ENC[AES256_GCM,data:xyoNxsCSAUConRliKXM6Ycbw+GIO4PYnAMIwH50GAjkdJNfT5yNFeypZpC3h6jJf8KiMFP8y8JGROwMSEMGBNz/zDqhoCj1b0tpmjd5WlrHBsS14u3D7GLrD3i4p1Jjd9o/9U9aYnIPnVpZqxgxlva9PPciywBXII4Y+2Dn9EIo=,iv:6r7LuIrFNGf30bxgzEDCVq6OkO7kYCZCImx6O+ZywJM=,tag:GEZpZC4FD61f4d42vzqj2g==,type:str]
    version: 3.13.2
