apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-info-dev
resources:
  - namespace.yaml
  - node-info-secrets.enc.yaml
  - ../base/node-info
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: node-info
      spec:
        chart:
          spec:
            valuesFiles:
              - charts/node-info/values.yaml
              - charts/node-info/values-dev.yaml
        values:
          image:
            repository: ghcr.io/cloudor-devops/node-info
            # Updated automatically by CI on every merge to main.
            tag: sha-72daa17
            pullSecrets:
              - name: ghcr-pull
          secret:
            existingSecret: node-info-secrets
