apiVersion: v1
kind: Secret
metadata:
    name: node-info-secrets
    namespace: node-info-dev
type: Opaque
stringData:
    API_TOKEN: ENC[AES256_GCM,data:8x7ifhSRBs/xVzAvaurGGJYjlYFQHw==,iv:aG+KMBvArLIOYWmlKjxoqDkJacqNEN4Id8hq+5n57x4=,tag:5NH/q42B1zQ+4PNVnWzzig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUnl2ZmVJMnY2bWhoLyt6
            Q0dzMUtxS0lqU3NMTENBSytjUlZVenhhTWowCjN1TGdQV3NtQ2VRaHBNTXU5WGVv
            T21wUnRRN2I3TzB4Rkx6K3JBVXJzSGcKLS0tIEpDdk9QdXBWSllHSVp3ZFhzVTBo
            MXQ3NStZaEVJeXZXb2QwUDB5enRVZUkKgEC8jDTRuEZjA+HN7J8A2vCgynT+TqhS
            1HVCctlbw8baXBMdaePZz2vOVzFFY1B73qVuyyq5wbed+p2R7tyaUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ynh89279chl2pd2rw4vkduy0vmxk999ryers7thh223wx3xeughstwue9v
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T07:23:01Z"
    mac: ENC[AES256_GCM,data:6PmORkxHpaUQZ4AWdMDw62m0h6CgjlXTz18AGddcb4z1pxoPCcOjYQvMyO+aPIGcq6F9kdeYUiqjkxey2RD794miPrmdao+UUYeYMScxHVzm8uMJH/gmBbqkTk/D+CU/6XfpR50AL7g10pSZ5fhE3ER1UVjc9yoEdfZSZJGOa6k=,iv:856ShoqnoE7d3wISGoxCHPCEKzIFpvW1XMf3DK3F6Wo=,tag:SDflDQPrVQZtSNE0sxZznw==,type:str]
    version: 3.13.2
